export const ROLES = {
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE',
  AUDITOR: 'AUDITOR',
  OPERATOR: 'OPERATOR',
} as const

export const CONTRACT_TYPES = {
  OPS: 'OPS',
  OBRA_LABOR: 'OBRA_LABOR',
  TERMINO_FIJO: 'TERMINO_FIJO',
  TERMINO_INDEFINIDO: 'TERMINO_INDEFINIDO',
} as const

export const DOCUMENT_TYPES = {
  CC: 'CC',
  CE: 'CE',
  PASAPORTE: 'PASAPORTE',
  REGISTRO_CIVIL: 'REGISTRO_CIVIL',
  TI: 'TI',
} as const

export const EMPLOYEE_STATUS = {
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
} as const

export const CLIENT_STATUS = {
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
} as const

export const NOTE_TYPES = {
  POSITIVA: 'POSITIVA',
  NEGATIVA: 'NEGATIVA',
  NEUTRAL: 'NEUTRAL',
  ALERTA: 'ALERTA',
} as const

export const NOTE_PRIORITY = {
  ALTA: 'ALTA',
  MEDIA: 'MEDIA',
  BAJA: 'BAJA',
} as const

export const NOTE_VISIBILITY = {
  TODOS: 'TODOS',
  SOLO_MEDICOS: 'SOLO_MEDICOS',
  SOLO_ADMIN: 'SOLO_ADMIN',
} as const

export const INSTRUMENT_TYPES = {
  VALORACION: 'VALORACION',
  NUTRICION: 'NUTRICION',
  MATRICULA: 'MATRICULA',
  ADMISION: 'ADMISION',
} as const

export const PERIODICIDAD = {
  UNICA: 'UNICA',
  ANUAL: 'ANUAL',
  MENSUAL: 'MENSUAL',
  TRIMESTRAL: 'TRIMESTRAL',
  SEMESTRAL: 'SEMESTRAL',
} as const

export const FICHA_STATUS = {
  COMPLETADO: 'COMPLETADO',
  PENDIENTE: 'PENDIENTE',
  VENCIDO: 'VENCIDO',
} as const

export const VACATION_STATUS = {
  APROBADO: 'APROBADO',
  PENDIENTE: 'PENDIENTE',
  RECHAZADO: 'RECHAZADO',
} as const

export const ABSENCE_CAUSES = {
  INCAPACIDAD: 'INCAPACIDAD',
  PRORROGA: 'PRORROGA',
  PERMISO: 'PERMISO',
  LICENCIA_NO_REMUNERADA: 'LICENCIA_NO_REMUNERADA',
  LICENCIA_LEGAL: 'LICENCIA_LEGAL',
} as const

export const LICENSE_TYPES = {
  MATERNIDAD: 'MATERNIDAD',
  PATERNIDAD: 'PATERNIDAD',
  LUTO: 'LUTO',
} as const

export const PREFACTURA_STATUS = {
  BORRADOR: 'BORRADOR',
  ENVIADO: 'ENVIADO',
  PAGADO: 'PAGADO',
} as const
